name: Simple CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Привіт, світ!"

      - name: Multi commands
        run: |
          echo "Тут можна додати збірку"
          echo "тести або інші дії"